apiVersion: v1
kind: ConfigMap
metadata:
  name: focalboard-config
  namespace: focalboard
data:
  config.json: |
    {
      "serverRoot": "https://focalboard.bourne.cloud",
      "port": 8000,
      "dbtype": "sqlite3",
      "dbconfig": "/opt/focalboard/data/focalboard.db",
      "filesdriver": "local",
      "filespath": "/opt/focalboard/data/files",
      "enableLocalMode": true,
      "localModeSocketLocation": "/var/tmp/focalboard_local.socket"
    }