apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: community-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://community-charts.github.io/helm-charts