# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: backup-target
#   namespace: longhorn-system
# data:
#   default-resource.yaml: |
#     "backup-target": "192.168.1.10:/mnt/storage-zfs/k8s-longhorn-backup"
#     "backupstore-poll-interval": "180"
# Not required according to Claude.AI???