apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.18.2   # Use the latest stable version
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      # optional: reconcileStrategy: ChartVersion
  values:
    installCRDs: true