apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: talos-z5r-24p             # must exactly match the k8s node name
  namespace: longhorn-system
spec:
  disks:
    vdb-disk:
      path: /var/lib/longhorn/disks/vdb
      allowScheduling: true
      storageReserved: 0