apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repos
  namespace: flux-system
spec:
  interval: 5m
  path: ../../repos
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn: 
    - name: namespaces