apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncast-data
  namespace: owncast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn