apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:gBUN85FyzueedpgfKooyh+70DUuw+WtqzhIQNn3cJetMLij7V8Zp8g==,iv:AsdnYaZdAQ/zgLYKSGIKv6MHsKU9lOZKggp2ruc93F8=,tag:BHNRGWt5CFg/ctCJ/XfPNA==,type:str]
sops:
    age:
        - recipient: age15dt7js8n0zr4znk3a5lu7d74krv4qqlh48xymvjy76cmplhn5qpqw9q0pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa2FiajFISmdaam0wK2J2
            clJTZjhuWjFyOCtDUEdodjhaQUNXNU1UZkdJCm1RTW9HU1FoZkxyL3dxRVZwMUhZ
            V2xheHgvK1VDTWtJeEcrUmtGVWVTcU0KLS0tIDk0V1V4T1ljMm00bEptN2FScGJ2
            Vmd1cGNjZmNvNDZzNmZjNXhTWmpaUG8Kr654XF9pb15ge3CGAlZS0UiGoMn7nVFp
            uP/Yx9WzkzYKHOQogN1gIKnsWg3VgUuRqYVaaZRijbEAAUHvz04UWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T12:30:45Z"
    mac: ENC[AES256_GCM,data:Prxoz1D0Qk1wCbx1RySK3JdrJFInL7VWzNnhAfpo2RT2wP1m2vGKi44BgU8W360SOyPvo/KUtj7gYYGxp7Ecu0xJeMGmPDwdbiwJ04bFI9Z+R7X7QuTHK1MxVbU8dkDWRQ5dLt7D57veyHa+y9JjFQ87mEXaUV+nWlQwswiWfmQ=,iv:nGOgeFAnD6Cx59dmFXDxCk3u7mSyBoregV6/UqIu6oA=,tag:TS3I+Qesq8eIMZstCG6Mew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0